# Generated by Django 3.2.12 on 2022-03-28 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izenburua', models.CharField(max_length=60)),
                ('zuzendaria', models.CharField(max_length=60)),
                ('urtea', models.IntegerField(max_length=11)),
                ('generoa', models.CharField(max_length=2)),
                ('sinopsia', models.CharField(max_length=700)),
                ('bozkak', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Bozkatzailea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erabiltzailea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gogokofilmak', models.ManyToManyField(to='app.Filma')),
            ],
        ),
    ]
